steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/smallweb:${SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/smallweb:${SHORT_SHA}']
  - name: google/cloud-sdk
    args: [
      'gcloud',
      'run',
      'deploy',
      'smallweb',
      '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/smallweb:${SHORT_SHA}',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--set-env-vars', 'URL_PREFIX=/smallweb',
      '--update-secrets', 'MOD_SECRET_KEY=smallweb-mod-secret-key:latest',
      '--service-account', 'smallweb@${PROJECT_ID}.iam.gserviceaccount.com',
      '--cpu=1',
      '--memory=1Gi',
      '--min-instances', '2',
      '--max-instances', '4'
    ]
images:
  - us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/smallweb:${SHORT_SHA}
